import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>William Lee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Product Advocate Position at <a href="https://vercel.com/">Vercel</a>
        </h1>

        <p className={styles.description}>
          Application submitted by{' '}
          <code className={styles.code}>William Lee</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>What I Might Do &darr;</h2>
            <h3>Most Interested In:</h3>
              <ol type="1">
                <li>Work with the Team to make sure email tone is consistent with the Vercel brand</li>
                <li>Hop on a Zoom call to do a product demo</li>
                <li>Recommend to customers the Vercel plan best suited for them</li>
              </ol> 
              <h3>Least Interested In:</h3>
              <ol type="1">
                <li>Research and organize notes to ensure Account Executives are prepared for calls</li>
                <li>Analyze sales inquiries to help spot trends in needs</li>
                <li>Evaluate OSS sponsorship applications</li>
              </ol> 
          </a>

          <a className={styles.card}>
            <h2>Reflection a. &darr;</h2>
              <p>Since this will be my first role in tech after graduating from BloomTech, I am looking to learn as much as I can. My goal in my next role is to really master the technical aspects of frontend frameworks and to be able to TEACH someone else what I know. In my eyes, if you can teach someone a skill, that is when you have mastered that skill.</p>
              </a>

          <a href='https://time.com/6158182/vitalik-buterin-ethereum-profile/' className={styles.card}>
            <h2>Reflection b. &rarr;</h2>
              <p>I have been interested in and watched the cryptocurrency space for a few years now, and an article in Time Magazine came out earlier this year talking about Vitalik Buterin -- the founder of Ethereum. To me it seemed that cryptocurrency had gotten away from what it was intended to do. The article explains how Buterin, although himself concerned, will evermore stand by the principles of an open-sourced, decentralized internet. It goes on to say that Ethereum will move to a proof of stake blockchain verification system, which will reduce energy usage by more than 99 percent. In short, the article just gives me hope that despite all the money that surrounds Buterin, he still stand by his morals and pushes forward for a decentralized future where banks and countries don't hold all the power. </p>
          </a>

          <a className={styles.card}>
            <h2>Personal Recommendations &darr;</h2>
              <p>Some of the common things to consider are bandwidth needs, how many team members need access, image optimization, security, and options for support. I would imagine the mom and pop business would need a lot less in terms of bandwidth, support options, and team member access, but still need plenty in terms of security since they are dealing with transactions. An NFT site would need a lot for image optimization and security, because you would be dealing with buying and selling of the images in all likelihood. A marketing page for Nintendo would require a lot of bandwidth and team member access, but perhaps not as much image optimization since it is just one page.    </p> 
          </a>

          <a className={styles.card}>
            <h2>Practice Email 1 &darr;</h2>
            <p>How are you doing Joe? Firstly, thank you for considering Vercel as a hosting option. I&apos;d be glad to walk you through our Enterprise option as that would certainly be a great fit for Barnes and Noble. I&apos;m sure as you saw some of the basic information from our site, but Enterprise is single-sign-on -- which we all love, and comes with a dedicated support manager to you and your team. Pricing is scaled according to your bandwidth needs. I&apos;d love to get some more details from you to better assist our potential partnership. If we could get on a call or zoom some time this week I would love to walk you through how Vercel works, as well as how Enterprise would be the perfect fit for your needs. Would some time today or tomorrow work for you? Look forward to hearing from you.</p>
          </a>

          <a className={styles.card}>
            <h2>Practice Email 2 &darr;</h2>
            <p>Hi Melissa, Thank you for reaching to Vercel for your hosting needs -- I&apos;d be happy to help. At first glance at your site, my initial guess would be that Enterprise would be the way to go for Hipcamp, but I can&apos;t say straight away which option would be better for you without knowing a bit more information. In terms of your timeline, I don&apos;t think there would be any issues. Are you available sometime today or tomorrow to hop on a call/zoom to discuss further? I can walk you through everything you need to know about our product and together we can make an informed decision about which option makes the most sense. Let me know what day and time would work best for you.   </p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
