import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>William Lee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Product Advocate Position at <a href="https://vercel.com/">Vercel</a>
        </h1>

        <p className={styles.description}>
          Application submitted by{' '}
          <code className={styles.code}>William Lee</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>What I Might Do &darr;</h2>
            <h3>Most Interested In:</h3>
              <ol type="1">
                <li>Work with the Team to make sure email tone is consistent with the Vercel brand</li>
                <li>Hop on a Zoom call to do a product demo</li>
                <li>Recommend to customers the Vercel plan best suited for them</li>
              </ol> 
              <h3>Least Interested In:</h3>
              <ol type="1">
                <li>Research and organize notes to ensure Account Executives are prepared for calls</li>
                <li>Analyze sales inquiries to help spot trends in needs</li>
                <li>Evaluate OSS sponsorship applications</li>
              </ol> 
          </a>

          <a className={styles.card}>
            <h2>Reflection &darr;</h2>
            <ol type="a">
              <li>Since this will be my first role in tech after graduating from BloomTech, I'm looking to learn as much as I can. My goal in my next role is to really master the technical aspects of frontend frameworks and to be able to TEACH someone else what I know. In my eyes, if you can teach someone a skill, that's when you've mastered that skill.</li>
              <li></li>
            </ol> 
          </a>

          <a className={styles.card}>
            <h2>Practice Emails &darr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a className={styles.card}>
            <h2>Personal Recommendations &darr;</h2>
            <h3>Most Interested In:</h3>
              <ol type="1">
                <li>mom n pop</li>
                <li>NFT</li>
                <li>Nintendo marketing page</li>
              </ol> 
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
